[project]
name = "multiagentesanalistaposts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "crewai>=0.121.1",
    "crewai-tools>=0.46.0",
    "langchain>=0.3.25",
    "playwright>=1.52.0",
    "python-dotenv>=1.1.0",
]
